(function (window) {
  window.__env = {
    production: true,
    testing: false,
    apiKeyPdf: '3279fe9a-0f72-4b0e-a2c2-6d3d210cda9c',
    siteUrl: 'https://escritoriovirtual.loovi.com.br',
    siteUrlLoovi: 'https://loovi.com.br',
    looviBase: 'https://core-api.loovi.com.br/',
    indicationEndpoint: 'https://core-api.loovi.com.br:8443/Api/Loovi/SaveIndication',
    getindicationEndpoint: 'https://core-api.loovi.com.br:8443/Api/Loovi/GetIndication',
    salesForceLead: 'https://c22093r8uj.execute-api.us-east-1.amazonaws.com/producao/salesforce/v1/cria-objeto/lead',
    proxyEndpoint: 'https://pag45vto72.execute-api.us-east-1.amazonaws.com/producao/v1',
    correiosEndpoint: 'https://c7508ju745.execute-api.us-east-1.amazonaws.com/producao/correios/v2',
    bucketS3Endpoint: 'https://rzx1zzmb53.execute-api.us-east-1.amazonaws.com/producao/buckets-s3/v1',
    cpfCnpjEndPoint: 'https://wczo319lv9.execute-api.us-east-1.amazonaws.com/producao/cpf-cnpj/v1',
    notaFiscalEndpoint: 'https://3egy6c6wa6.execute-api.us-east-1.amazonaws.com/producao/upload-nota/v1',
    consultaVeiculo: 'https://4vcq2mdo13.execute-api.us-east-1.amazonaws.com/producao/consulta-veiculos/v1',
    novaproxyEndpoint: 'https://pag45vto72.execute-api.us-east-1.amazonaws.com/producao/v1',
    recuperacaoSenhaEndpoint: 'https://af3ee145ee.execute-api.us-east-1.amazonaws.com/producao/usuario/v1',
    migracaoExecutivo: 'https://migracaowordpress.loovi.com.br/migracao',
    autenticacaoExecutivoEndpoint: 'https://e2ib2uw05e.execute-api.us-east-1.amazonaws.com/producao/autenticacao/v1',
    checkout: 'https://loovi.com.br/checkout/',
    requester: 'Portal',
    bucketS3: {
      looviCobre: 'pdf-loovi-cobre-us-east-1',
      fotoPerfil: 'foto-perfil-escritorio-us-east-1',
      region: 'us-east-2',
    },
    strapi: 'https://conteudo.loovi.com.br',
    executivoBaseUrl: 'https://executivo.loovi.com.br',
    pdfBucketName: 'pdf-clientes-loovi-lti',
    api2pdfUrl: 'https://v2.api2pdf.com/chrome/pdf/html',
    planilhaApiUrl: 'https://sheet.best/api/sheets/6de89b4d-7d38-43bc-a683-372b894d9850',
    googleAnalyticsId: 'G-6389RT9DFB',
    sentryDsn: 'https://742312564646f33f868ecc8e35e761d3@o4511408672669696.ingest.us.sentry.io/4511413923545088',
    sentryEnv: 'production',
    sentryRelease: '10c66a16b5122caea1a074b14e2756cd468a078d',
  };
})(this);
